name: Generate snake game

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          #palette: github-dark
          #color_snake: red
          #color_dots: green, blue, purple, 
          github_user_name: ${{ github.repository_owner }}
          outputs: | 
            dist/snake.svg
            dist/snake.svg?palette=github-dark
            dist/snake.svg?color_snake=red&color_dots=#444444,#38761d,#3d85c6,#16537e,#6a329f


      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}